In [ ]:
aList = ["John", 33, "Toronto", True]
print(aList)

['John', 33, 'Toronto', True]


In [ ]:
import datetime as dt
tanggal = dt.date.today()
mahasiswa = ["Rais", "2023071043", "Informatika", "DAA", tanggal, "Universitas Pembangunan Jaya"]
print(mahasiswa)

['Rais', '2023071043', 'Informatika', 'DAA', datetime.date(2024, 9, 20), 'Universitas Pembangunan Jaya']


In [ ]:
print(mahasiswa[0])

Rais


In [ ]:
print (aList[3])

True


In [ ]:
print(aList[0])

John


In [ ]:
print ("Nim:", mahasiswa[1])

Nim: 2023071043


In [ ]:
print("Nama Kampus :", mahasiswa[5])

Nama Kampus : Universitas Pembangunan Jaya


In [ ]:
warna=["Merah", "Biru", "Kuning", "Hijau"]
warna[2:4]

['Kuning', 'Hijau']

In [ ]:
warna=["Merah", "Biru", "Kuning", "Hijau"]
for aWarna in warna:
   print(aWarna, "Kotak")


Merah Kotak
Biru Kotak
Kuning Kotak
Hijau Kotak


In [ ]:
mahasiswa = ["Rais", "2023071043", "Informatika", "DAA", str(tanggal), "Universitas Pembangunan Jaya"]
for aMahasiswa in mahasiswa:
 print(aMahasiswa, "UPJ")

Rais UPJ
2023071043 UPJ
Informatika UPJ
DAA UPJ
2024-09-20 UPJ
Universitas Pembangunan Jaya UPJ


In [45]:
UPJ = ("Universitas", "Pembangunan", "Jaya")
UPJ[2]

'Jaya'

In [47]:
import pandas as pd


data = {
    'NO': ['1', '2', '3',],
    'Prodi': ['INF', 'SIF', 'TM'],
    'Mahasiswa': [80, 55, 45],
    'Lakilaki': [79, 30, 35],
    'Perempuan': [1, 25, 10]
}


mhs = pd.DataFrame(data)


print(mhs)


  NO Prodi  Mahasiswa  Lakilaki  Perempuan
0  1   INF         80        79          1
1  2   SIF         55        30         25
2  3    TM         45        35         10


In [48]:
AngkaPertama = 100
AngkaKedua = (200, 400, 600)
AngkaKetiga = 300
AngkaKeempat = (400, 800)

print(AngkaPertama)

100


In [49]:
AngkaSemua = (
    100,
    (200, 400, 600),
    300,
    (400, 800)
)


print(AngkaSemua)

(100, (200, 400, 600), 300, (400, 800))


In [50]:
def pisahkan_warna(kata_kata):


  warna_kata = {'yellow': set(), 'red': set()}
  warna_dominan = {'yellow': {'dandelions', 'leaves'}, 'red': {'blood', 'rose', 'fire hydrant'}}

  for kata in kata_kata:
    for warna in warna_dominan:
      if kata in warna_dominan[warna]:
        warna_kata[warna].add(kata)

  return warna_kata

kata_kata = {'blood', 'rose', 'dandelions', 'fire hydrant', 'leaves'}
hasil = pisahkan_warna(kata_kata)
print(hasil)

{'yellow': {'leaves', 'dandelions'}, 'red': {'fire hydrant', 'blood', 'rose'}}


In [53]:
import numpy as np

angkaangka = np.array([[100, 200, 300], [700, 600, 500], [900, 1000, 800]])
print(angkaangka)

[[ 100  200  300]
 [ 700  600  500]
 [ 900 1000  800]]
